const TechnicalSkills = {
  'Programming Languages': [
    'JavaScript',
    'Python',
    'TypeScript',
    'Ruby',
    'HTML',
    'EJS',
    'CSS',
    'SASS',
    'SQL',
  ],
  'Libraries/Frameworks': [
    'Node.js',
    'Express.js',
    'React',
    'Redux',
    'jQuery',
    'Axios',
    'AJAX',
    'Ruby on Rails',
    'Mongoose',
    'Bootstrap',
  ],
  Testing: ['Mocha', 'Chai', 'Jest', 'Storybook', 'Cypress', 'Rspec'],
  'Database Management': ['PostgreSQL', 'MongoDB'],
  Development: [
    'Git',
    'Github',
    'Visual Studio Code',
    'Linux',
    'Postman',
    'Heroku',
    'Vercel',
    'Netlify',
    'Figma',
  ],
};
module.exports = {
  TechnicalSkills,
};
